name: actions_secrets

on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Print secret directly
    - name: Print Secret
      run: |
        echo "MY_TOP_SECRET: ${{ secrets.MY_TOP_SECRET }}"
        echo "MY_TOP_SECRET: ${{ secrets.not_created_secret }}"
    # Print secret as env
    - name: Print Secret as Environment Variable
      run: |
        echo "MY_TOP_SECRET: ${{ env.MY_SECRET }}"
      # Secret as env variable
      env:
        MY_SECRET: ${{ secrets.MY_TOP_SECRET }}
    # Check if adHoc secret value is censored to
    - name: T
      run: |
        echo "MY_TOP_SECRET: ${{ secrets.MY_TOP_SECRET }}"
        echo "top"
