name: actions_artifacts

on:
  push:


jobs:

  # create artifact
  upload_artifact:
    runs-on: ubuntu-latest
    steps:

    # Create File
    - name: CreateFile
      run: echo "File Content" > file1.txt

    # Upload artifact to GitHub
    - name: Upload a single artifact
      uses: actions/upload-artifact@v4
      with:
        name: file1
        path: file1.txt
        retention_days: 10

  # download artifact
  download_artifact:
    runs-on: ubuntu-latest

    # Add dependency to avoid parallel execution and artifact not ready
    needs: upload_artifact
    steps:

    # Add artifact on runner
    - name: Download a single artifact
      uses: actions/download-artifact@v4
      with:
        name: file1

    # Uses artifact
    - name: DisplayFile
      run: cat file1.txt
