name: CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
    - master
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
    - master

  # Allows running manually from the actions tab
  workflow_dispatch:


jobs:
  # test_schedule --> is the only job
  test_schedule:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: hello
      run: echo "Hello World"
