name: CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
    - master
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
    - master

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
    - name: hello
      run: echo "Hello World"
